# Generated by Django 3.1.6 on 2021-04-24 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('OpenTourList', '0002_item_text'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tourist',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('code', models.CharField(max_length=11, unique=True)),
                ('destination', models.TextField()),
                ('reservationDate', models.DateField()),
                ('purpose', models.CharField(choices=[('HM', 'Home'), ('BU', 'Business'), ('GA', 'Getaway'), ('OT', 'Others')], default='HM', max_length=2)),
            ],
        ),
        migrations.DeleteModel(
            name='Item',
        ),
    ]
