# Generated by Django 3.1.6 on 2021-04-28 09:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('OpenTourList', '0005_tourist'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='TourId',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.PROTECT, to='OpenTourList.tourist'),
        ),
    ]
