# Generated by Django 3.1.6 on 2021-04-29 14:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('OpenTourList', '0006_item_tourid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='TourId',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='OpenTourList.tourist'),
        ),
    ]
