# Generated by Django 3.1.6 on 2021-04-29 15:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('OpenTourList', '0007_auto_20210429_1447'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='TourId',
        ),
        migrations.RemoveField(
            model_name='item',
            name='text',
        ),
        migrations.AddField(
            model_name='tourist',
            name='TourId',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='OpenTourList.item'),
        ),
        migrations.AddField(
            model_name='tourist',
            name='text',
            field=models.TextField(default=''),
        ),
    ]
