# Generated by Django 3.1.6 on 2021-05-10 10:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('OpenTourList', '0010_auto_20210502_2346'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Tourist',
            new_name='Recruit',
        ),
        migrations.RemoveField(
            model_name='item',
            name='TourId',
        ),
        migrations.AddField(
            model_name='item',
            name='RecId',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='OpenTourList.Tourist'),
        ),
    ]
