# Generated by Django 3.1.6 on 2021-05-13 17:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('OpenTourList', '0011_auto_20210510_1024'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Recruit',
            new_name='Tourist',
        ),
        migrations.RenameField(
            model_name='item',
            old_name='RecId',
            new_name='TourId',
        ),
    ]
